version: '3.8'
services:
    postgres:
        image: postgres:13.0
        restart: always
        shm_size: 128mb
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: 123
            POSTGRES_HOST: localhost
            POSTGRES_DBL: demo
        ports:
            - 5432:5432
    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080